---
# the game name
name: "MudForge"

# TLS data - this must be paths to PEM and KEY files.
tls:
  ca: "ca.pem"
  cert: "cert.pem"
  key: "key.key"

# Interfaces - Internal will be used for IPC, external for clients
interfaces:
  internal: "127.0.0.1" # this should never change...
  external: "0.0.0.0"

# external ports used by telnet connections.
# Omit them to disable.
telnet:
  plain: 7999
  tls: 7998

# external ports used by (game client) websocket connections
# Omit them to disable.
websocket:
  plain: 7997
  tls: 7996

# external port used by SSH. This doesn't have a TLS version because
# SSH has its own encryption.
# Omit to disable.
ssh: 7995

# external ports used by the webserver
# Omit them to disable.
website:
  plain: 80
  tls: 443

# Classes used by the game for various purposes. Add your own!
classes:
  telnet_protocol: "mudforge.net.telnet.TelnetMudConnection"
  game_connection: "mudforge.net.game_conn.GameConnection"

# Services launched when the game boots.
services:
  telnet: "mudforge.services.telnet.TCPTelnetServerService"
  #  telnets: "mudforge.services.telnet.TLSTelnetServerService"
  game: "adventkai.game.GameService"

# Python modules to auto-load Modifiers from.
modifiers:
  - "adventkai.modifiers.admin_flags"
  - "adventkai.modifiers.affects"
  - "adventkai.modifiers.bonuses"
  - "adventkai.modifiers.item_flags"
  - "adventkai.modifiers.item_types"
  - "adventkai.modifiers.mob_flags"
  - "adventkai.modifiers.player_flags"
  - "adventkai.modifiers.positions"
  - "adventkai.modifiers.preference_flags"
  - "adventkai.modifiers.races"
  - "adventkai.modifiers.room_flags"
  - "adventkai.modifiers.room_sectors"
  - "adventkai.modifiers.sensei"
  - "adventkai.modifiers.wear_flags"
  - "adventkai.modifiers.zone_flags"

hooks:
  pre_start: "adventkai.hooks.pre_start"
  early_launch: "adventkai.hooks.early_launch"

# python modules to auto-load Components from.
components:
  - "adventkai.components"
